"""Deterministic rules the workflow applies to an LLM decision (safe in workflow code).

The reasoning Activity already validated the decision, but the workflow is the
authority and does not trust model output: it re-checks the tool against the
fixed registry and the supervisor's enabled tools, enforces a single tool,
checks required inputs, clamps the wake interval, and caps memory.
No I/O, no randomness, no clock: every input is passed in.
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from app.temporal.constants import (
    MEMORY_CONCERN_MAX_CHARS,
    MEMORY_MAX_OPEN_CONCERNS,
    MEMORY_SUMMARY_MAX_CHARS,
)
from app.temporal.contracts import FinalOutputContent, ReasoningDecision
from app.tools.registry import TOOL_SPECS, missing_required_inputs


@dataclass
class ValidatedDecision:
    # The single tool to execute, or None.
    tool: Optional[str]
    tool_input: Dict[str, Any] = field(default_factory=dict)
    # Why a requested tool was refused (None if accepted or none requested).
    rejection_reason: Optional[str] = None
    wake_minutes: int = 0


def clamp_wake_interval(requested: Optional[int], default: int, minimum: int, maximum: int) -> int:
    """LLM-requested interval bounded to [minimum, maximum]; default when absent/invalid."""
    if not isinstance(requested, int) or isinstance(requested, bool):
        return default
    return max(minimum, min(maximum, requested))


def validate_decision(
    decision: ReasoningDecision,
    *,
    enabled_tools: List[str],
    default_wake: int,
    min_wake: int,
    max_wake: int,
) -> ValidatedDecision:
    tool = decision.tool
    tool_input = {k: v for k, v in (decision.tool_input or {}).items() if v is not None}
    rejection: Optional[str] = None

    if tool is not None:
        if not isinstance(tool, str):
            # e.g. a list: more than one tool (or a malformed field) is never executed.
            rejection = "exactly one tool name is allowed per reasoning cycle"
        elif tool not in TOOL_SPECS:
            rejection = f"unknown tool {tool!r}"
        elif tool not in enabled_tools:
            rejection = f"tool {tool!r} is not enabled for this supervisor"
        else:
            missing = missing_required_inputs(tool, tool_input)
            if missing:
                rejection = f"tool {tool!r} is missing required inputs {missing}"

    return ValidatedDecision(
        tool=None if rejection else tool,
        tool_input={} if rejection or tool is None else tool_input,
        rejection_reason=rejection,
        wake_minutes=clamp_wake_interval(decision.next_wake_in_minutes, default_wake, min_wake, max_wake),
    )


def initial_memory() -> Dict[str, Any]:
    return {
        "situation_summary": "",
        "open_concerns": [],
        "last_action": None,
        "last_wake_reason": None,
        "cycle_count": 0,
    }


def updated_memory(
    decision: ReasoningDecision,
    *,
    last_action: Optional[str],
    wake_reason: str,
    cycle_count: int,
) -> Dict[str, Any]:
    """New compact memory: LLM-owned fields (capped) + workflow-owned metadata."""
    concerns = [str(c)[:MEMORY_CONCERN_MAX_CHARS] for c in (decision.open_concerns or [])]
    return {
        "situation_summary": str(decision.situation_summary or "")[:MEMORY_SUMMARY_MAX_CHARS],
        "open_concerns": concerns[:MEMORY_MAX_OPEN_CONCERNS],
        "last_action": last_action,
        "last_wake_reason": wake_reason,
        "cycle_count": cycle_count,
    }


def fallback_final_output(
    *,
    order_id: str,
    final_order_status: Optional[str],
    memory: Dict[str, Any],
    action_log: List[Dict[str, Any]],
    events_received: int,
    reasoning_count: int,
    failure: str,
) -> FinalOutputContent:
    """Deterministic final output built only from recorded workflow state."""
    failed = [a for a in action_log if not a.get("success")]
    summary = (
        f"Order {order_id} reached terminal status {final_order_status!r} after "
        f"{reasoning_count} reasoning cycle(s) and {events_received} event(s); "
        f"{len(action_log)} tool execution(s), {len(failed)} failed."
    )
    if memory.get("situation_summary"):
        summary += f" Last recorded situation: {memory['situation_summary']}"
    return FinalOutputContent(
        summary=summary,
        key_actions=[
            f"{a['tool']}: {'succeeded' if a.get('success') else 'failed'}" for a in action_log
        ],
        key_learnings=[
            "Generated by the deterministic fallback because LLM final-output generation failed: "
            + failure
        ],
        recommendations=["Review this run's timeline and tool executions manually."],
    )
